import streamlit as st
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
from dashboard.components.theme import inject_custom_css, check_results

inject_custom_css()
results = check_results()
task_outputs = results.get("task_outputs", [])

# Header
st.markdown("""
<div class="hero-header" style="background: linear-gradient(135deg, #f39c12 0%, #e67e22 50%, #d35400 100%);">
    <h1>💡 Research Ideas</h1>
    <p>Novel research ideas generated by AI based on identified gaps, limitations, and emerging trends</p>
</div>
""", unsafe_allow_html=True)

# Find ideas output
ideas_output = ""
for task in task_outputs:
    desc = task.get("task", "").lower()
    if "idea" in desc:
        ideas_output = task.get("output", "")

if ideas_output:
    st.markdown("""
    <div class="info-banner">
        <h4>💡 AI-Generated Research Ideas</h4>
        <p>Each idea is synthesized from research gaps, paper limitations, and citation network patterns. Ideas include feasibility assessment, novelty evaluation, and resource requirements.</p>
    </div>
    """, unsafe_allow_html=True)

    st.markdown(ideas_output)
else:
    st.markdown("""
    <div class="empty-state">
        <div class="empty-icon">💡</div>
        <h3>No Research Ideas Generated</h3>
        <p>Run a full analysis to generate novel research ideas based on gaps and limitations.</p>
    </div>
    """, unsafe_allow_html=True)

st.markdown('<hr class="section-divider">', unsafe_allow_html=True)

# Full crew output
st.markdown("### 📋 Complete Analysis Report")
crew_output = results.get("crew_output", "")
if crew_output:
    with st.expander("View full CrewAI output", expanded=False):
        st.markdown(crew_output)
else:
    st.info("Full output will appear here after analysis completes.")
